### ISSUE TITLE
consider including links to github pull requests pushed out in the tag

### ISSUE THREAD

**Issue by willkg** [mozilla-services/obs-common#9]
Currently, the release script captures all the commits that were pushed out with a release. However, commits don't include conversation about what changed.

It'd be good to include the list of pull requests pushed out with a release. I think we can do that by looking at the commit range, then using the github graphql API to figure out what pull requests cover that range.

From https://github.com/willkg/socorro-release/issues/34

**Comment by relud** [comment]
pull requests are automatically linked, see for example: https://github.com/mozilla-services/obs-common/releases/tag/v2024.08.14-1
